"""initial schema

Revision ID: 4f30aab9c35c
Revises: 
Create Date: 2026-03-20 20:20:02.717778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f30aab9c35c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_lines', 'pnl_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'opex'::character varying"))
    op.alter_column('budget_lines', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_budget_lines_plan_type'), table_name='budget_lines')
    op.alter_column('invoices', 'match_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unmatched'::character varying"))
    op.create_foreign_key(None, 'invoices', 'purchase_orders', ['purchase_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'match_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unmatched'::character varying"))
    op.create_index(op.f('idx_budget_lines_plan_type'), 'budget_lines', ['plan_type'], unique=False)
    op.alter_column('budget_lines', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('budget_lines', 'pnl_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'opex'::character varying"))
    # ### end Alembic commands ###
